### ISSUE TITLE
TypeError: modalLabel.bringToTop is not a function

### ISSUE THREAD

**Issue by vitorregisrr** [netgfx/phaser_modals#10]
Hey. I'm trying to use your script, but its not working here.
I'm receiving the error TypeError: modalLabel.bringToTop is not a function.
I'm using the 2.0 version, maybe its de problem?
When i remove all the bringtotop lines its work, but not show the modals.

**Comment by netgfx** [comment]
Hello, which Phaser version are you using (2.6.2)? or Latest CE?

Also please add the complete code of the modal making so I can probably spot the bug.

**Comment by vitorregisrr** [comment]
I'm using the 2.0 version. I tried to update to 2.62 but this giveme the error TypeError: Argument 6 is not valid for any of the 6-argument overloads of WebGLRenderingContext.texImage2D.

My modals code is:
var reg = {};

function createModals() {
    reg.modal.createModal({
        type: "gameOverModal",
        includeBackground: false,
        modalCloseOnInput: true,
        itemsArr: [{
                type: "image",
                content: "levelFailed",
                offsetY: -20,
                contentScale: 1
            },
            {
                type: "image",
                content: "clear",
                contentScale: 0.5,
                offsetY: -80
            },
            {
                type: "image",
                content: "star",
                offsetY: 80,
                offsetX: -100,
                contentScale: 0.6
            },
            {
                type: "image",
                content: "star",
                offsetY: 50,
                offsetX: 0,
                contentScale: 0.6
            },
            {
                type: "image",
                content: "star",
                offsetY: 80,
                offsetX: 100,
                contentScale: 0.6
            },
            {
                type: "text",
                content: "X",
                fontSize: 52,
                color: "0x000000",
                offsetY: -130,
                offsetX: 240,
                callback: function () {
                    reg.modal.hideModal("modal5");
                }
            }

        ]
    });

    reg.modal.createModal({
        type: "countDownModal",
        includeBackground: true,
        backgroundColor: "0xffffff",
        backgroundOpacity: 0.8,
        itemsArr: [{
                type: "text",
                content: "Starting \nNext Level",
                fontFamily: "Luckiest Guy",
                fontSize: 52,
                offsetY: -100
            },
            {
                type: "text",
                content: "5",
                fontFamily: "Luckiest Guy",
                fontSize: 42,
                offsetY: 0
            }
        ]
    });
}


function showGameOverModal() {
    reg.modal.showModal("gameOverModal");
}

function showCountDownModal() {
    reg.modal.showModal("countDownModal");
    countDown(updateCountdown, function () {
        reg.modal.hideModal("modal6");
    });
}

function countDown(fn, endFn) {
    var endFn = endFn || function () {};

    var _timer = game.time.create(false);
    _timer.start();
    _timer.onComplete.add(endFn);
    _timer.repeat(Phaser.Timer.SECOND, 5, fn, this);
    window.console.log("adding timer", game);
}

function updateCountdown() {
    var item = reg.modal.getModalItem("modal6", 3);
    var index = Number(item.text);

    window.console.log("index: ", index, item);

    item.setText(String(index - 1));
    item.update();
    item.x = game.width / 2 - (item.width / 2);
    item.y = game.height / 2 - (item.height / 2);
}

**Comment by vitorregisrr** [comment]
I'm using the 2.0 version. I tried to update to 2.62 but this giveme the error TypeError: Argument 6 is not valid for any of the 6-argument overloads of WebGLRenderingContext.texImage2D.

My modals code is:
https://github.com/vitorregisrr/destruaasmutacoesgame/blob/master/js/modalsGen.js

**Comment by netgfx** [comment]
Are you at some point doing: `reg.modal = new gameModal(game);` ?

**Comment by netgfx** [comment]
Also I would suggest trying out the Phaser CE version it fixes most of 2.6.2 issues
https://github.com/photonstorm/phaser-ce/releases
(CE = Community Edition)

**Comment by vitorregisrr** [comment]
Yeah, i have removed it for continue coddind the game.

**Comment by netgfx** [comment]
you need to add it before calling `createModals` probably on boot

**Comment by vitorregisrr** [comment]
Now i'm having other bug.
I called the reg.modal on gameLoad.
var game = new Phaser.Game(800, 600, Phaser.WEBGL,'#game');
reg.modal = new gameModal(game);

After i tried to call the game over modal on startState create function:

function criarStart(){
    showGameOverModal();
    [...]
}

and i'm having it.
![image](https://user-images.githubusercontent.com/9900252/43097685-35369ff2-8e93-11e8-8871-af242d1f0858.png)

Alsoo, i tried to update my phaser lib, but i'm having the error t.source is null phaser when i replace the old library file with the new one.

**Comment by vitorregisrr** [comment]
the error hapens only when i try to call the modal on startState.
![image](https://user-images.githubusercontent.com/9900252/43097832-b857be3e-8e93-11e8-9fba-19ee04f5f948.png)

**Comment by netgfx** [comment]
it says on the top that the library is still Phaser 2.0.1 first console log

Also make sure to 
1) do `reg.modal = new gameModal(game);`
2) call `createModal();`
3) then call showGameOverModal()

**Comment by vitorregisrr** [comment]
As I said, I'm having problems updating the lib, when I replace the old version with the new one I get errors.

**Comment by vitorregisrr** [comment]
![image](https://user-images.githubusercontent.com/9900252/43100826-e1fe41a0-8e9c-11e8-9631-b28e03ddc3c1.png)
the error that i said. i cant update my lib.

**Comment by netgfx** [comment]
Are you using typescript or simple javascript?

**Comment by samme** [comment]
Use the unminified Phaser script (phaser.js).

If you see an error in the console, expand it.

If the assets fail to load you probably need to run a local web server.

**Comment by vitorregisrr** [comment]
Im using simple javascript.
Im trying to use the unminified, but the error still happens.
![image](https://user-images.githubusercontent.com/9900252/43104515-1c9b7c64-8ea8-11e8-9010-1f812d2d752c.png)

**Comment by netgfx** [comment]
Do you have the complete source code somewhere so I can take a look? The issue is not modal related anymore but I'll try to help.

**Comment by vitorregisrr** [comment]
yeah, i  really apreciate your help.
you can se the source code here: https://github.com/vitorregisrr/destruaasmutacoesgame
