### ISSUE TITLE
bitmapText  typeError

### ISSUE THREAD

**Issue by vitorregisrr** [netgfx/phaser_modals#16]
I'm receiving the error TypeError: this._data is null when using bitmaptext.
I tryied the label type text and everthing works without error. I can't find where is the error, can you helpme?

the label is: 
```
 {
                type: "bitmapText",
                fontSize: 21,
                content: "Alternativa 2",
                offsetY: 20,
                offsetX: -60,
                callback: function (e) {
                }
            },
```

**Comment by vitorregisrr** [comment]
The problem isnt with the plugin, i dont know why but my game dont accept bitmap text, i tryied the following code and i had the same error.
`game.add.bitmapText(200, 100, 'Arial', 'BitmapText', 64);`

**Comment by netgfx** [comment]
This error doesn't make sense without more context. Have you tried adding bitmap text without the plugin? I mean without calling a modal around the lines where you declare the bitmap text? Maybe something else is failing, look into `this._data` in your code.

**Comment by vitorregisrr** [comment]
Look what i said xD

**Comment by netgfx** [comment]
I saw, closing this issue since it is not directly related to the plugin. Ask around on the Phaser Slack Channel, or PM me there (@michaeld)

**Comment by vitorregisrr** [comment]
Github disabled pm.
Can i call you on email? 
And...  did you see my pull request?

**Comment by netgfx** [comment]
@vitorregisrr I would prefer if you contact me on Phaser Slack, because email doesn't display code snippets the right way.
I did see the pull request, but will have to take a closer look when I can because there are some major changes there.
