### ISSUE TITLE
Possible to use this in Phaser 3.55.2?

### ISSUE THREAD

**Issue by alzen8blockchain** [netgfx/phaser_modals#18]
Possible to use this in Phaser 3.55.2?

as for now i tried it show black screen as shown below:
https://codepen.io/alzen8blockchain/pen/oNpBvvQ

![image](https://user-images.githubusercontent.com/98107883/159837150-053dc89d-8961-4ae8-a89b-6e4bacada8b3.png)

![image](https://user-images.githubusercontent.com/98107883/159837066-83ac323b-5def-48ef-a63f-7b277a3a4c09.png)

**Comment by netgfx** [comment]
Hello, unfortunately this is not possible because this plugin was meant to be used for Phaser version 2, which is not compatible with Phaser 3 out of the box.
I could probably create a new plugin for Phaser 3 on a new repository

**Comment by alzen8blockchain** [comment]
Hi Michael Dobekidis,

Thx for the reply ya. So... any plans for creating the plugin anytime soon?
If not, just seeking your advice on any existing plugin you might recommend
perhaps?

**Comment by netgfx** [comment]
Well the easiest thing you could do is create a new scene and display it on top of the existing scene (which is pretty much what a modal does)
Check this out: https://gist.github.com/netgfx/80aec3bac44d48d7c484f7b84a923794

You can open it like:
```
 this.modalScene = this.scene.launch('ModalMissionScene', {
      parentScene: this,
 });

this.modalScene.bringToTop();
```
